package io.doindev.cvector.cli.commands;

import io.doindev.cvector.cli.CvectorRuntime;
import io.doindev.cvector.core.config.CvectorConfig;
import io.doindev.cvector.neo4j.Neo4jClient;
import io.doindev.cvector.neo4j.repo.GraphQueries;
import org.springframework.stereotype.Component;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import java.util.concurrent.Callable;

@Component
@Command(name = "wiki", description = "Generate Markdown documentation for the active project from the graph.")
public class WikiCommand implements Callable<Integer> {

    @Option(names = {"--out", "-o"}, required = true, description = "Output directory (created if missing).")
    private Path outDir;

    private final CvectorRuntime runtime;

    public WikiCommand(CvectorRuntime runtime) {
        this.runtime = runtime;
    }

    @Override
    public Integer call() throws IOException {
        CvectorConfig cfg = runtime.loadConfig();
        CvectorConfig.ProjectEntry active = runtime.requireActiveProject(cfg);
        Path target = outDir.toAbsolutePath().normalize();
        Files.createDirectories(target);

        try (Neo4jClient client = runtime.openNeo4j(cfg)) {
            GraphQueries q = new GraphQueries(client);
            String pid = active.projectId();
            String now = ZonedDateTime.now().toString();

            writeIndex(target, active, q, pid, now);
            writeFiles(target, q, pid);
            writeClasses(target, q, pid);
            writeEndpoints(target, q, pid);
            writeTables(target, q, pid);
            writeConfig(target, q, pid);
            writeDependencies(target, q, pid);
        }

        System.out.println("wiki generated at " + target);
        return 0;
    }

    private void writeIndex(Path dir, CvectorConfig.ProjectEntry active, GraphQueries q, String pid, String now) throws IOException {
        Map<String, Long> nodes = q.nodeCounts(pid);
        Map<String, Long> edges = q.edgeCounts(pid);
        StringBuilder s = new StringBuilder();
        s.append("# ").append(active.name()).append("\n\n");
        s.append("_Generated by cvector at ").append(now).append("_\n\n");
        s.append("- **Project ID**: `").append(active.projectId()).append("`\n");
        s.append("- **Root path**: `").append(active.rootPath()).append("`\n\n");
        s.append("## Graph size\n\n");
        s.append("| Label | Count |\n|---|---:|\n");
        nodes.forEach((k, v) -> s.append("| ").append(k).append(" | ").append(v).append(" |\n"));
        s.append("\n## Edges\n\n| Type | Count |\n|---|---:|\n");
        edges.forEach((k, v) -> s.append("| ").append(k).append(" | ").append(v).append(" |\n"));
        s.append("\n## Sections\n\n");
        s.append("- [Files](files.md)\n");
        s.append("- [Classes](classes.md)\n");
        s.append("- [REST endpoints](endpoints.md)\n");
        s.append("- [Tables](tables.md)\n");
        s.append("- [Configuration](config.md)\n");
        s.append("- [Dependencies](dependencies.md)\n");
        Files.writeString(dir.resolve("index.md"), s.toString());
    }

    private void writeFiles(Path dir, GraphQueries q, String pid) throws IOException {
        List<Map<String, Object>> rows = q.raw(
                "MATCH (f:File {projectId: $pid}) "
                        + "OPTIONAL MATCH (f)-[:CONTAINS]->(c:Class) "
                        + "RETURN f.path AS path, f.language AS language, count(c) AS classes "
                        + "ORDER BY f.path",
                Map.of("pid", pid));
        StringBuilder s = new StringBuilder();
        s.append("# Files\n\n");
        s.append("| Path | Language | Classes |\n|---|---|---:|\n");
        for (Map<String, Object> r : rows) {
            s.append("| `").append(esc(r.get("path"))).append("` | ")
                    .append(esc(r.get("language"))).append(" | ")
                    .append(r.get("classes")).append(" |\n");
        }
        Files.writeString(dir.resolve("files.md"), s.toString());
    }

    private void writeClasses(Path dir, GraphQueries q, String pid) throws IOException {
        List<Map<String, Object>> classes = q.raw(
                "MATCH (c:Class {projectId: $pid}) "
                        + "OPTIONAL MATCH (c)-[:CONTAINS]->(m:Method) "
                        + "WITH c, count(m) AS methodCount "
                        + "WHERE c.kind IS NOT NULL "
                        + "RETURN c.fqName AS fqName, c.kind AS kind, methodCount "
                        + "ORDER BY methodCount DESC, c.fqName",
                Map.of("pid", pid));
        StringBuilder s = new StringBuilder();
        s.append("# Classes\n\n");
        s.append("| Class | Kind | Methods |\n|---|---|---:|\n");
        for (Map<String, Object> r : classes) {
            s.append("| `").append(esc(r.get("fqName"))).append("` | ")
                    .append(esc(r.get("kind"))).append(" | ")
                    .append(r.get("methodCount")).append(" |\n");
        }
        Files.writeString(dir.resolve("classes.md"), s.toString());
    }

    private void writeEndpoints(Path dir, GraphQueries q, String pid) throws IOException {
        List<Map<String, Object>> rest = q.raw(
                "MATCH (e:ApiEndpoint {projectId: $pid})-[:HANDLES]->(m:Method) "
                        + "RETURN e.httpMethod AS httpMethod, e.path AS path, m.fqName AS handler "
                        + "ORDER BY path",
                Map.of("pid", pid));
        List<Map<String, Object>> consumers = q.raw(
                "MATCH (m:Method {projectId: $pid}) WHERE coalesce(m.isQueueListener, false) = true "
                        + "RETURN m.fqName AS handler ORDER BY m.fqName",
                Map.of("pid", pid));
        StringBuilder s = new StringBuilder();
        s.append("# REST endpoints + queue surface\n\n");
        s.append("## REST endpoints\n\n");
        if (rest.isEmpty()) s.append("_(none)_\n");
        else {
            s.append("| Method | Path | Handler |\n|---|---|---|\n");
            for (Map<String, Object> r : rest) {
                s.append("| ").append(esc(r.get("httpMethod"))).append(" | `")
                        .append(esc(r.get("path"))).append("` | `")
                        .append(esc(r.get("handler"))).append("` |\n");
            }
        }
        s.append("\n## Queue / topic consumers\n\n");
        if (consumers.isEmpty()) s.append("_(none)_\n");
        else {
            s.append("| Handler |\n|---|\n");
            for (Map<String, Object> r : consumers) {
                s.append("| `").append(esc(r.get("handler"))).append("` |\n");
            }
        }
        Files.writeString(dir.resolve("endpoints.md"), s.toString());
    }

    private void writeTables(Path dir, GraphQueries q, String pid) throws IOException {
        List<Map<String, Object>> tables = q.raw(
                "MATCH (t:Table {projectId: $pid}) "
                        + "OPTIONAL MATCH (t)-[:CONTAINS]->(c:Column) "
                        + "RETURN t.name AS table, collect({name: c.name, type: c.type}) AS columns "
                        + "ORDER BY t.name",
                Map.of("pid", pid));
        StringBuilder s = new StringBuilder();
        s.append("# Database tables\n\n");
        if (tables.isEmpty()) s.append("_(none)_\n");
        for (Map<String, Object> t : tables) {
            String name = String.valueOf(t.get("table"));
            s.append("## `").append(name).append("`\n\n");
            @SuppressWarnings("unchecked")
            List<Map<String, Object>> cols = (List<Map<String, Object>>) t.get("columns");
            if (cols == null || cols.isEmpty() || (cols.size() == 1 && cols.get(0).get("name") == null)) {
                s.append("_(no columns recorded — was the CREATE TABLE in scope?)_\n\n");
                continue;
            }
            s.append("| Column | Type |\n|---|---|\n");
            for (Map<String, Object> c : cols) {
                if (c == null || c.get("name") == null) continue;
                s.append("| ").append(esc(c.get("name"))).append(" | ").append(esc(c.get("type"))).append(" |\n");
            }
            s.append("\n");
        }
        Files.writeString(dir.resolve("tables.md"), s.toString());
    }

    private void writeConfig(Path dir, GraphQueries q, String pid) throws IOException {
        List<Map<String, Object>> keys = q.raw(
                "MATCH (k:ConfigKey {projectId: $pid}) RETURN k.fqName AS key, k.value AS value ORDER BY k.fqName",
                Map.of("pid", pid));
        List<Map<String, Object>> envs = q.raw(
                "MATCH (e:EnvVar {projectId: $pid}) RETURN e.name AS name, e.value AS value ORDER BY e.name",
                Map.of("pid", pid));
        StringBuilder s = new StringBuilder();
        s.append("# Configuration\n\n");
        s.append("## Config keys (YAML/JSON/properties)\n\n");
        if (keys.isEmpty()) s.append("_(none)_\n");
        else {
            s.append("| Key | Value |\n|---|---|\n");
            for (Map<String, Object> k : keys) {
                s.append("| `").append(esc(k.get("key"))).append("` | `").append(esc(k.get("value"))).append("` |\n");
            }
        }
        s.append("\n## Environment variables (.env)\n\n");
        if (envs.isEmpty()) s.append("_(none)_\n");
        else {
            s.append("| Name | Value |\n|---|---|\n");
            for (Map<String, Object> e : envs) {
                s.append("| ").append(esc(e.get("name"))).append(" | `").append(esc(e.get("value"))).append("` |\n");
            }
        }
        Files.writeString(dir.resolve("config.md"), s.toString());
    }

    private void writeDependencies(Path dir, GraphQueries q, String pid) throws IOException {
        List<Map<String, Object>> deps = q.raw(
                "MATCH (d:MavenDependency {projectId: $pid}) "
                        + "RETURN d.groupId AS groupId, d.artifactId AS artifactId, d.version AS version, d.scope AS scope "
                        + "ORDER BY groupId, artifactId",
                Map.of("pid", pid));
        StringBuilder s = new StringBuilder();
        s.append("# Dependencies\n\n");
        s.append("| Group | Artifact | Version | Scope |\n|---|---|---|---|\n");
        for (Map<String, Object> d : deps) {
            s.append("| ").append(esc(d.get("groupId"))).append(" | ")
                    .append(esc(d.get("artifactId"))).append(" | ")
                    .append(esc(d.get("version"))).append(" | ")
                    .append(esc(d.get("scope"))).append(" |\n");
        }
        Files.writeString(dir.resolve("dependencies.md"), s.toString());
    }

    private static String esc(Object o) {
        if (o == null) return "";
        return String.valueOf(o).replace("|", "\\|").replace("\n", " ");
    }
}
