package io.doindev.cvector.cli.commands;

import io.doindev.cvector.cli.CvectorRuntime;
import io.doindev.cvector.core.config.CvectorConfig;
import io.doindev.cvector.core.store.GraphStore;
import org.springframework.stereotype.Component;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import java.util.concurrent.Callable;

@Component
@Command(name = "wiki", description = "Generate Markdown documentation for the active project from the graph.", mixinStandardHelpOptions = true)
public class WikiCommand implements Callable<Integer> {

    @Option(names = {"--out", "-o"}, required = true, description = "Output directory (created if missing).")
    private Path outDir;

    private final CvectorRuntime runtime;

    public WikiCommand(CvectorRuntime runtime) {
        this.runtime = runtime;
    }

    @Override
    public Integer call() throws IOException {
        CvectorConfig cfg = runtime.loadConfig();
        CvectorConfig.ProjectEntry active = runtime.requireActiveProject(cfg);
        Path target = outDir.toAbsolutePath().normalize();
        Files.createDirectories(target);

        try (GraphStore store = runtime.openGraphStore(cfg)) {
            String pid = active.projectId();
            String now = ZonedDateTime.now().toString();

            writeIndex(target, active, store, pid, now);
            writeFiles(target, store, pid);
            writeClasses(target, store, pid);
            writeEndpoints(target, store, pid);
            writeTables(target, store, pid);
            writeConfig(target, store, pid);
            writeDependencies(target, store, pid);
        }

        System.out.println("wiki generated at " + target);
        return 0;
    }

    private void writeIndex(Path dir, CvectorConfig.ProjectEntry active, GraphStore store, String pid, String now) throws IOException {
        Map<String, Long> nodes = store.nodeCounts(pid);
        Map<String, Long> edges = store.edgeCounts(pid);
        StringBuilder s = new StringBuilder();
        s.append("# ").append(active.name()).append("\n\n");
        s.append("_Generated by cvector at ").append(now).append("_\n\n");
        s.append("- **Project ID**: `").append(active.projectId()).append("`\n");
        s.append("- **Root path**: `").append(active.rootPath()).append("`\n");
        s.append("- **Backend**: `").append(store.backend()).append("`\n\n");
        s.append("## Graph size\n\n");
        s.append("| Label | Count |\n|---|---:|\n");
        nodes.forEach((k, v) -> s.append("| ").append(k).append(" | ").append(v).append(" |\n"));
        s.append("\n## Edges\n\n| Type | Count |\n|---|---:|\n");
        edges.forEach((k, v) -> s.append("| ").append(k).append(" | ").append(v).append(" |\n"));
        s.append("\n## Sections\n\n");
        s.append("- [Files](files.md)\n");
        s.append("- [Classes](classes.md)\n");
        s.append("- [REST endpoints](endpoints.md)\n");
        s.append("- [Tables](tables.md)\n");
        s.append("- [Configuration](config.md)\n");
        s.append("- [Dependencies](dependencies.md)\n");
        Files.writeString(dir.resolve("index.md"), s.toString());
    }

    private void writeFiles(Path dir, GraphStore store, String pid) throws IOException {
        List<Map<String, Object>> rows = store.fileInventory(pid);
        StringBuilder s = new StringBuilder();
        s.append("# Files\n\n");
        s.append("| Path | Language | Methods | Last ingested |\n|---|---|---:|---|\n");
        for (Map<String, Object> r : rows) {
            s.append("| `").append(esc(r.get("path"))).append("` | ")
                    .append(esc(r.get("language"))).append(" | ")
                    .append(r.get("methodCount") != null ? r.get("methodCount") : 0).append(" | ")
                    .append(esc(r.get("lastIngestedAt"))).append(" |\n");
        }
        Files.writeString(dir.resolve("files.md"), s.toString());
    }

    private void writeClasses(Path dir, GraphStore store, String pid) throws IOException {
        // Top classes via onboardSummary covers the highest-method-count ones; for full coverage
        // we leverage searchByName with a "*" wildcard restricted to label=Class. Sorting is
        // alphabetical from the search; method counts pulled per-class via contains.
        List<Map<String, Object>> classes = store.searchByName(pid, "*", "Class", 1000);
        StringBuilder s = new StringBuilder();
        s.append("# Classes\n\n");
        s.append("| Class | Methods |\n|---|---:|\n");
        for (Map<String, Object> r : classes) {
            String id = String.valueOf(r.get("id"));
            int methodCount = store.contains(pid, id, 1000).size();
            s.append("| `").append(esc(r.get("fqName"))).append("` | ")
                    .append(methodCount).append(" |\n");
        }
        Files.writeString(dir.resolve("classes.md"), s.toString());
    }

    private void writeEndpoints(Path dir, GraphStore store, String pid) throws IOException {
        Map<String, List<Map<String, Object>>> infra = store.infrastructureSummary(pid);
        List<Map<String, Object>> rest = infra.getOrDefault("apiEndpoints", List.of());
        List<Map<String, Object>> consumers = infra.getOrDefault("queueListeners", List.of());
        StringBuilder s = new StringBuilder();
        s.append("# REST endpoints + queue surface\n\n");
        s.append("## REST endpoints\n\n");
        if (rest.isEmpty()) s.append("_(none)_\n");
        else {
            s.append("| Method | Path | Framework |\n|---|---|---|\n");
            for (Map<String, Object> r : rest) {
                s.append("| ").append(esc(r.get("httpMethod"))).append(" | `")
                        .append(esc(r.get("path"))).append("` | ")
                        .append(esc(r.get("framework"))).append(" |\n");
            }
        }
        s.append("\n## Queue / topic consumers\n\n");
        if (consumers.isEmpty()) s.append("_(none)_\n");
        else {
            s.append("| Handler |\n|---|\n");
            for (Map<String, Object> r : consumers) {
                s.append("| `").append(esc(r.get("fqName"))).append("` |\n");
            }
        }
        Files.writeString(dir.resolve("endpoints.md"), s.toString());
    }

    private void writeTables(Path dir, GraphStore store, String pid) throws IOException {
        // onboardSummary's tables list has {table, columns}. For a per-column drill-down,
        // searchByName for Column nodes filtered by tableId would be ideal, but is more queries.
        Map<String, List<Map<String, Object>>> onboard = store.onboardSummary(pid);
        List<Map<String, Object>> tables = onboard.getOrDefault("tables", List.of());
        StringBuilder s = new StringBuilder();
        s.append("# Database tables\n\n");
        if (tables.isEmpty()) s.append("_(none)_\n");
        else {
            s.append("| Table | Columns |\n|---|---:|\n");
            for (Map<String, Object> t : tables) {
                s.append("| `").append(esc(t.get("table"))).append("` | ")
                        .append(t.get("columns") != null ? t.get("columns") : 0).append(" |\n");
            }
        }
        Files.writeString(dir.resolve("tables.md"), s.toString());
    }

    private void writeConfig(Path dir, GraphStore store, String pid) throws IOException {
        Map<String, List<Map<String, Object>>> infra = store.infrastructureSummary(pid);
        List<Map<String, Object>> keys = infra.getOrDefault("configKeys", List.of());
        List<Map<String, Object>> envs = infra.getOrDefault("envVars", List.of());
        StringBuilder s = new StringBuilder();
        s.append("# Configuration\n\n");
        s.append("## Config keys (YAML/JSON/properties)\n\n");
        if (keys.isEmpty()) s.append("_(none)_\n");
        else {
            s.append("| Key |\n|---|\n");
            for (Map<String, Object> k : keys) {
                s.append("| `").append(esc(k.get("fqName"))).append("` |\n");
            }
        }
        s.append("\n## Environment variables (.env)\n\n");
        if (envs.isEmpty()) s.append("_(none)_\n");
        else {
            s.append("| Name | Value |\n|---|---|\n");
            for (Map<String, Object> e : envs) {
                s.append("| ").append(esc(e.get("fqName"))).append(" | `").append(esc(e.get("value"))).append("` |\n");
            }
        }
        Files.writeString(dir.resolve("config.md"), s.toString());
    }

    private void writeDependencies(Path dir, GraphStore store, String pid) throws IOException {
        List<Map<String, Object>> deps = store.mavenDependencies(pid);
        StringBuilder s = new StringBuilder();
        s.append("# Dependencies\n\n");
        s.append("| Group | Artifact | Version | Scope |\n|---|---|---|---|\n");
        for (Map<String, Object> d : deps) {
            s.append("| ").append(esc(d.get("groupId"))).append(" | ")
                    .append(esc(d.get("artifactId"))).append(" | ")
                    .append(esc(d.get("version"))).append(" | ")
                    .append(esc(d.get("scope"))).append(" |\n");
        }
        Files.writeString(dir.resolve("dependencies.md"), s.toString());
    }

    private static String esc(Object o) {
        if (o == null) return "";
        return String.valueOf(o).replace("|", "\\|").replace("\n", " ");
    }
}
